version: '3'

services:
  go-app:
    build: .
    container_name: goapp
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/

  postgres:
    build: ./.docker/postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: gerenciador_de_eventos
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ~/volumes/gerenciador_de_eventos/postgres:/var/lib/postgresql/data